[workspace]
members = [
    "api_2048",
    "app_2048",
    "types_2048",
]
resolver = "2"

[workspace.dependencies]
atrium-api = "0.25.2"
atrium-common = "0.1.1"
atrium-identity = "0.1.3"
atrium-oauth = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
